#      /$$$$$$        /$$                                                         /$$
#     /$$__  $$      | $$                                                        | $$|
#    | $$  \ $$  /$$$$$$$ /$$    /$$ /$$$$$$  /$$$$$$$   /$$$$$$$  /$$$$$$   /$$$$$$$|
#    | $$$$$$$$ /$$__  $$|  $$  /$$/|____  $$| $$__  $$ /$$_____/ /$$__  $$ /$$__  $$|
#    | $$__  $$| $$  | $$ \  $$/$$/  /$$$$$$$| $$  \ $$| $$      | $$$$$$$$| $$  | $$|
#    | $$  | $$| $$  | $$  \  $$$/  /$$__  $$| $$  | $$| $$      | $$_____/| $$  | $$|
#    | $$  | $$|  $$$$$$$   \  $/  |  $$$$$$$| $$  | $$|  $$$$$$$|  $$$$$$$|  $$$$$$$|
#    |__/  |__/ \_______/    \_/    \_______/|__/  |__/ \_______/ \_______/ \_______/
######################################################################################


###############################################################
#      # The language to use in the /language folder          #
#                  Default: english                           #
# List: "english" "french" "dutch" "german" "italian"         #
#       "korean" "norwegian" "russian" "spanish" "turkish"    #
###############################################################
language: "english"